"
    Copyright (c) 2020 Aucerna.
    See (MIT) license in root directory.
"

Package { #name : #IR,
	#classes : [
		'BMNullaryOperation',
		'OActivationContext',
		'OBasicBlock',
		'OBeginInstruction',
		'OBinaryConstantOperation',
		'OBinaryOperation',
		'OBinaryVariableOperation',
		'OBlockClosure',
		'OComposedLiveRange',
		'OConstant',
		'ODefineArgument',
		'ODominatorTree',
		'OEndInstruction',
		'OInstruction',
		'OJump',
		'OJumpConditional',
		'OJumpFalse',
		'OJumpTrue',
		'OLiveRange',
		'OLoadConstant',
		'OLoadImplicit',
		'OMessageSend',
		'OOperand',
		'OPhi',
		'OPrimitiveOperation',
		'OReadVariable',
		'OReturn',
		'OSimpleLiveRange',
		'OTemporary',
		'OTernaryOperation',
		'OTiling',
		'OUnaryOperation',
		'OUseVariable',
		'OValue',
		'OVariable',
		'OWriteVariable'
	]
}

