"
	Copyright (c) 2021 Quorum Software.
	See (MIT) license in root directory.
"

Package {
	#name : #LMR, 
	#classes : [
		'CopyingCollector',
		'CriticalArray',
		'DispatchSite',
		'DummyGlobalDispatchCache',
		'EdenCollector',
		'GCSpace',
		'GlobalDispatchCache',
		'LookupSite',
		'Memory',
		'NativeCode',
		'ObjectGraph',
		'ReifiedStackFrameCursor',
		'SendSite',
		'StackChunk',
		'StackFrameCursor',
		'StackWrapper',
		'Thread',
	]
}