"
    Copyright (c) 2020 Aucerna. 
    Copyright (c) 2008-2019 The Pharo Project, and Contributors.
    See (MIT) license in root directory.
"

Package { #name : #Parsers,
	#classes : [
		'PPActionParser',
		'PPAndParser',
		'PPCharSetPredicate',
		'PPChoiceParser',
		'PPDelegateParser',
		'PPEndOfInputParser',
		'PPEpsilonParser',
		'PPFailingParser',
		'PPFlattenParser',
		'PPListParser',
		'PPLiteralObjectParser',
		'PPLiteralParser',
		'PPLiteralSequenceParser',
		'PPMappedParser',
		'PPMemoizedParser',
		'PPNotParser',
		'PPOptionalParser',
		'PPParser',
		'PPPluggableParser',
		'PPPredicateObjectParser',
		'PPPredicateParser',
		'PPPredicateSequenceParser',
		'PPRepeatingParser',
		'PPSequencedChoiceParser',
		'PPSequenceParser',
		'PPTokenParser',
		'PPTrimmingParser',
		'PPWrappingParser'
	]
}

