#ifndef _KNOWNCONSTANTS_H_
#define _KNOWNCONSTANTS_H_

/**
 *  These constants may be autogenerated from the contents of
 *  Kernel module in the future
 */

namespace Egg {

enum BlockFlags {
    CapturesHome = 0x800000,
    CapturesSelf = 0x400000
};

enum BlockCapturedVariables {
    Self = 0,
    LocalArgument = 1,
    Environment = 2,
    EnvironmentValue = 3,
    OuterInlinedArgument = 4
};

enum MethodFlags {
    MethodArgCount = 0x3F,
    MethodTempCount = 0x1FE000,
    MethodTempCountShift = 13,
    MethodIsExtension = 0x80000000
};

enum Offsets {
    AssociationKey = 0,
    AssociationValue = 1,

    BehaviorClass = 0,
    BehaviorMethodDictionary = 1,
    BehaviorNext = 2,

    BlockFormat = 0,
    BlockExecutableCode = 1,
    BlockMethod = 2,

    ClosureBlock = 0,

    DictionaryTally = 0,
    DictionaryTable = 1,

    MethodFormat = 0,
    MethodExecutableCode = 1,
    MethodTreecodes = 2,
    MethodClassBinding = 3,
    MethodSelector = 4,
    MethodSourceCode = 5,
    MethodInstSize = 6,

    FFIMethodDescriptor = 6,
    FFIMethodSymbol = 7,
    FFIMethodAddress = 8,

    ModuleName = 0,
    ModuleVersion = 1,
    ModuleExports = 2,
    ModuleNamespace = 3,

	SpeciesSuperclass = 0,
	SpeciesInstanceBehavior = 1,
	SpeciesFormat = 2,
	SpeciesOrganization = 3,
	SpeciesInstanceVariables = 4,
    ClassName = 5,
    ClassSubclasses = 6,
    ClassNamespaces = 7,
    ClassModule = 8,
    MetaclassClass = 5,

    CompiledCodeExecutableCode = 1,

    ExecutableCodePlatformCode = 0,
    ExecutableCodeCompiledCode = 1,

    FFI_uint8 = 0,
    FFI_sint8 = 1,
    FFI_uint16 = 2,
    FFI_sint16 = 3,
    FFI_uint32 = 4,
    FFI_sint32 = 5,
    FFI_uint64 = 6,
    FFI_sint64 = 7,
    
    FFI_float = 8,
    FFI_double = 9,

    FFI_uchar = 10,
    FFI_schar = 11,
    FFI_ushort = 12,
    FFI_sshort = 13,
    FFI_uint = 14,
    FFI_sint = 15,
    FFI_ulong = 16,
    FFI_slong = 17,
    FFI_longdouble = 18,

    FFI_pointer = 19,

    FFI_complex_float = 20,
    FFI_complex_double = 21,
    FFI_complex_longdouble = 22,

    FFI_void = 23
};

} // namespace Egg

#endif // ~ _KNOWNCONSTANTS_H_ ~
